#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    z = int(input())
   
    count = 0;
    while(z!= 0):
        z = (z & (z << 1)) 
   
        count=count+1
    
    print(count)

    
   
    
